<a href="https://colab.research.google.com/github/idarwati/BelajarPython/blob/main/PythonMasterclass/Belajar_indexing_Kapal_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# Ganti ID dengan file kamu
file_id = '1kQHNP1cpFw-44yTaEcbLrvBKY_CtUDwj'
url = f'https://drive.google.com/uc?id={file_id}'

In [ ]:
# Untuk CSV
dataku = pd.read_csv(url)

In [ ]:
dataku

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [ ]:
data_baru = dataku['age']

In [ ]:
data_baru

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
type(data_baru)

pandas.core.series.Series

In [ ]:
dataku [['age','fare']]

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [ ]:
type(dataku)

pandas.core.frame.DataFrame

Dot notation

In [ ]:
dataku.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
dataku['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
dataku.age.equals(dataku['age'])

True

iloc

.iloc[baris,kolom]

In [ ]:
dataku.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [ ]:
dataku.iloc[0]

survived       0
pclass         3
sex         male
age         22.0
sibsp          1
parch          0
fare        7.25
embarked       S
deck         NaN
Name: 0, dtype: object

In [ ]:
dataku.iloc[0:10]

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN
5         0       3    male   NaN      0      0   8.4583        Q  NaN
6         0       1    male  54.0      0      0  51.8625        S    E
7         0       3    male   2.0      3      1  21.0750        S  NaN
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [ ]:
dataku.iloc[:,3] #memilih semua baris, kolom 3

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
dataku.iloc[-5:]

     survived  pclass     sex   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [ ]:
dataku.tail()

     survived  pclass     sex   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [ ]:
dataku.iloc[[0,2,4]] #baris

   survived  pclass     sex   age  sibsp  parch   fare embarked deck
0         0       3    male  22.0      1      0  7.250        S  NaN
2         1       3  female  26.0      0      0  7.925        S  NaN
4         0       3    male  35.0      0      0  8.050        S  NaN

In [ ]:
dataku.iloc[[0,2,4],[1,3,6]] #baris, kolom

   pclass   age   fare
0       3  22.0  7.250
2       3  26.0  7.925
4       3  35.0  8.050

loc

.loc['nama baris', 'nama kolom']

In [ ]:
data_baru = pd.read_csv(url)

In [ ]:
data_baru.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [ ]:
data_baru = pd.read_csv(url, index_col='embarked')

In [ ]:
data_baru

          survived  pclass     sex   age  sibsp  parch     fare deck
embarked
S                0       3    male  22.0      1      0   7.2500  NaN
C                1       1  female  38.0      1      0  71.2833    C
S                1       3  female  26.0      0      0   7.9250  NaN
S                1       1  female  35.0      1      0  53.1000    C
S                0       3    male  35.0      0      0   8.0500  NaN
...            ...     ...     ...   ...    ...    ...      ...  ...
S                0       2    male  27.0      0      0  13.0000  NaN
S                1       1  female  19.0      0      0  30.0000    B
S                0       3  female   NaN      1      2  23.4500  NaN
C                1       1    male  26.0      0      0  30.0000    C
Q                0       3    male  32.0      0      0   7.7500  NaN

[891 rows x 8 columns]

In [ ]:
data_baru.loc['S']

          survived  pclass     sex   age  sibsp  parch     fare deck
embarked
S                0       3    male  22.0      1      0   7.2500  NaN
S                1       3  female  26.0      0      0   7.9250  NaN
S                1       1  female  35.0      1      0  53.1000    C
S                0       3    male  35.0      0      0   8.0500  NaN
S                0       1    male  54.0      0      0  51.8625    E
...            ...     ...     ...   ...    ...    ...      ...  ...
S                0       2    male  28.0      0      0  10.5000  NaN
S                0       3    male  25.0      0      0   7.0500  NaN
S                0       2    male  27.0      0      0  13.0000  NaN
S                1       1  female  19.0      0      0  30.0000    B
S                0       3  female   NaN      1      2  23.4500  NaN

[644 rows x 8 columns]

In [ ]:
data_baru.loc['S','age'] #1baris, 1kolom

embarked
S    22.0
S    26.0
S    35.0
S    35.0
S    54.0
     ...
S    28.0
S    25.0
S    27.0
S    19.0
S     NaN
Name: age, Length: 644, dtype: float64

In [ ]:
data_baru.loc['S',['age','fare']] # 1 baris, 2 kolom

           age     fare
embarked
S         22.0   7.2500
S         26.0   7.9250
S         35.0  53.1000
S         35.0   8.0500
S         54.0  51.8625
...        ...      ...
S         28.0  10.5000
S         25.0   7.0500
S         27.0  13.0000
S         19.0  30.0000
S          NaN  23.4500

[644 rows x 2 columns]

In [ ]:
data_baru.loc[['S','Q'],['age','fare']] # 2 baris, 2 kolom

           age     fare
embarked
S         22.0   7.2500
S         26.0   7.9250
S         35.0  53.1000
S         35.0   8.0500
S         54.0  51.8625
...        ...      ...
Q          NaN   7.7500
Q          NaN   6.9500
Q          NaN   7.7500
Q         39.0  29.1250
Q         32.0   7.7500

[721 rows x 2 columns]